all: compile_general execute_general

# COMPILERS INSTANCES
# gcc -o practica-01-fork-01 practica-01-fork-01.c
# gcc -o practica-01-fork-01 practica-01-fork-02.c
# gcc -o practica-01-fork-01 practica-01-fork-03.c
# gcc -o practica-01-fork-01 practica-01-fork-04.c
# gcc -o practica-01-fork-01 practica-01-fork-05.c
# gcc -o practica-01-fork-01 practica-01-fork-06.c
# gcc -o practica-01-fork-01 practica-01-fork-07.c
compile_general:
	gcc -o practica-01-fork-01 practica-01-fork-08.c

# EXECUTERS INSTANCES
execute_general:
	./practica-01-fork-01